# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ilc < Formula
  desc "Simplify creating command-line utilities"
  homepage "https://github.com/evilmarty/ilc"
  version "0.18.0"
  license "GPL"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evilmarty/ilc/releases/download/v0.18.0/ilc-0.18.0-darwin_amd64"
      sha256 "cd9f6c52db5b19c4ddbe1813615e6e94179631293e9f97b77cf33e8c94dd741c"

      def install
        bin.install Dir["*"].first => "ilc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evilmarty/ilc/releases/download/v0.18.0/ilc-0.18.0-darwin_arm64"
      sha256 "199896f1a99f5ae9b78d6530a74fff9711c54c5860170c51b3cb4ccea52d9eab"

      def install
        bin.install Dir["*"].first => "ilc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/evilmarty/ilc/releases/download/v0.18.0/ilc-0.18.0-linux_amd64"
        sha256 "2b914e8f669e3d5dff7ecd1fae00efdae368501c7855b95b76d49a6a9febb319"

        def install
          bin.install Dir["*"].first => "ilc"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/evilmarty/ilc/releases/download/v0.18.0/ilc-0.18.0-linux_armv6"
        sha256 "c3482461864a1bb9f25ef89f278b2b16dcba2174682ea55405c5d41a4edeaccc"

        def install
          bin.install Dir["*"].first => "ilc"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/evilmarty/ilc/releases/download/v0.18.0/ilc-0.18.0-linux_arm64"
        sha256 "c331c9201353a5282b25b5227a315e07d690d2219df61b3b770ac990259f5523"

        def install
          bin.install Dir["*"].first => "ilc"
        end
      end
    end
  end

  head "https://github.com/evilmarty/ilc.git", branch: "main"

  test do
    system "#{bin}/ilc", "--version"
  end
end
