# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ilc < Formula
  desc "Simplify creating command-line utilities"
  homepage "https://github.com/evilmarty/ilc"
  version "0.13.1"
  license "GPL"

  on_macos do
    on_intel do
      url "https://github.com/evilmarty/ilc/releases/download/v0.13.1/ilc-0.13.1-darwin_amd64"
      sha256 "2272cd2cc6be044b848153ac975fe8894a8409423f3b77b766593b4d15a2872a"

      def install
        bin.install Dir["*"].first => "ilc"
      end
    end
    on_arm do
      url "https://github.com/evilmarty/ilc/releases/download/v0.13.1/ilc-0.13.1-darwin_arm64"
      sha256 "ae9c3bd01ed8281e1dfbfe1274432ac241adfbd39e0a3fe816bbc88d6a3ddb3f"

      def install
        bin.install Dir["*"].first => "ilc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/evilmarty/ilc/releases/download/v0.13.1/ilc-0.13.1-linux_amd64"
        sha256 "d39e09bb81d433cf5f5526eb5dccd8f6edbf2164249270abdfb38d04f90d215e"

        def install
          bin.install Dir["*"].first => "ilc"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/evilmarty/ilc/releases/download/v0.13.1/ilc-0.13.1-linux_armv6"
        sha256 "2bb7555612f165a89d2eea108a28f05a6112e92104ac22e2a386c4174236464b"

        def install
          bin.install Dir["*"].first => "ilc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/evilmarty/ilc/releases/download/v0.13.1/ilc-0.13.1-linux_arm64"
        sha256 "934d872dd24990770c4490dcf8156b8c9ff542ccf5e0523e32a482654b4edaea"

        def install
          bin.install Dir["*"].first => "ilc"
        end
      end
    end
  end

  head "https://github.com/evilmarty/ilc.git", branch: "main"

  test do
    system "#{bin}/ilc", "--version"
  end
end
